---
- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - libpq-dev

- name: Install python virtualenv
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - pip
    - virtualenv

- name: Install python requirements
  pip:
    requirements: "{{ project_path }}/api/requirements.txt"
    virtualenv: "{{ project_path }}/api/venv"
    virtualenv_python: python3
