---
- name: Add current user to audio groups
  become: yes
  user:
    append: yes
    groups: audio
    name: "{{ ansible_user }}"

- name: Add mopidy's PPA key
  become: yes
  apt_key: url=https://apt.mopidy.com/mopidy.gpg

- name: Add mopidy's PPA
  become: yes
  apt_repository: repo={{ item }}
  with_items:
    - "deb http://apt.mopidy.com/ jessie main contrib non-free"
    - "deb-src http://apt.mopidy.com/ jessie main contrib non-free"

- name: Install required packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - libpq-dev
    - libasound2-dev
    - libffi-dev
    - libspotify-dev

- name: Install python virtualenv
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - pip
    - virtualenv

- name: Install python requirements
  pip:
    requirements: "{{ project_path }}/core/requirements.txt"
    virtualenv: "{{ project_path }}/core/venv"
    virtualenv_python: python3
